# Generated by Django 3.0.8 on 2020-07-18 06:15

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('product_title', models.CharField(max_length=255)),
                ('product_image_link', models.TextField()),
                ('product_shortlink', models.URLField()),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('product_details', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
