# Generated by Django 3.0.8 on 2020-07-18 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='details_length',
            field=models.IntegerField(blank=True, default=-1),
        ),
        migrations.AddField(
            model_name='deal',
            name='image_size',
            field=models.CharField(blank=True, choices=[('L', 'Large'), ('M', 'Medium'), ('S', 'Small')], default='L', max_length=1),
        ),
        migrations.AddField(
            model_name='deal',
            name='title_length',
            field=models.IntegerField(blank=True, default=-1),
        ),
    ]
